Bump the minor-dependencies group with 3 updates (#514)
Bumps the minor-dependencies group with 3 updates:
[no.nav.security:token-client-spring](https://github.com/navikt/token-support),
[no.nav.security:token-validation-spring-test](https://github.com/navikt/token-support)
and
[org.springframework.boot](https://github.com/spring-projects/spring-boot).

Updates `no.nav.security:token-client-spring` from 3.1.9 to 3.2.0
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/navikt/token-support/releases">no.nav.security:token-client-spring's
releases</a>.</em></p>
<blockquote>
<h2>3.2.0</h2>
<h2>What's Changed</h2>
<ul>
<li>bump to 3.2, add parameters option to compiler (<a
href="https://redirect.github.com/navikt/token-support/issues/802">#802</a>)
<a
href="https://github.com/jan-olaveide"><code>@​jan-olaveide</code></a></li>
<li>ci: add workflow for auto-merging dependabot PRs (<a
href="https://redirect.github.com/navikt/token-support/issues/793">#793</a>)
<a href="https://github.com/tronghn"><code>@​tronghn</code></a></li>
</ul>
<h2>⬆️ Dependency upgrades</h2>
<ul>
<li>build(deps): bump com.nimbusds:oauth2-oidc-sdk from 11.6 to 11.7 (<a
href="https://redirect.github.com/navikt/token-support/issues/799">#799</a>)
<a
href="https://github.com/dependabot"><code>@​dependabot</code></a></li>
<li>build(deps): bump kotlin.version from 1.9.20 to 1.9.21 (<a
href="https://redirect.github.com/navikt/token-support/issues/796">#796</a>)
<a
href="https://github.com/dependabot"><code>@​dependabot</code></a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/navikt/token-support/commit/4e3c487118c451d56f984a6ef72499a15c522e70"><code>4e3c487</code></a>
Merge pull request <a
href="https://redirect.github.com/navikt/token-support/issues/802">#802</a>
from navikt/bump-32</li>
<li><a
href="https://github.com/navikt/token-support/commit/9b7d08cc6d634183a45979e0084aca8fb144d808"><code>9b7d08c</code></a>
parameters in mor modules</li>
<li><a
href="https://github.com/navikt/token-support/commit/e22d741dffe4850f9f6e567f8e4e809e372638b1"><code>e22d741</code></a>
typo in pom</li>
<li><a
href="https://github.com/navikt/token-support/commit/55d9b0e1981297e1800f7701388a653f50b241e6"><code>55d9b0e</code></a>
bump to 3.2, add paraeters option to compiler</li>
<li><a
href="https://github.com/navikt/token-support/commit/907d5957ccf07440b1d2ec0ce1d227a318e9b1fa"><code>907d595</code></a>
build(deps): bump com.nimbusds:oauth2-oidc-sdk from 11.6 to 11.7 (<a
href="https://redirect.github.com/navikt/token-support/issues/799">#799</a>)</li>
<li><a
href="https://github.com/navikt/token-support/commit/4cdec36b59812fc844bf5e2cd8db508f10388f10"><code>4cdec36</code></a>
parameters maven</li>
<li><a
href="https://github.com/navikt/token-support/commit/7f6b6969aca45e1a44f68d41ed36f587b17dd430"><code>7f6b696</code></a>
mvn</li>
<li><a
href="https://github.com/navikt/token-support/commit/0dc9fee78801dac9dadcf53342fb63326b6ccdc4"><code>0dc9fee</code></a>
fix login</li>
<li><a
href="https://github.com/navikt/token-support/commit/f6b06502238bde2276d8249c3cd4fa053b92826e"><code>f6b0650</code></a>
fix login</li>
<li><a
href="https://github.com/navikt/token-support/commit/892b828478f912ceb15855f80252df15a24ca570"><code>892b828</code></a>
build(deps): bump kotlin.version from 1.9.20 to 1.9.21 (<a
href="https://redirect.github.com/navikt/token-support/issues/796">#796</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/navikt/token-support/compare/3.1.9...3.2.0">compare
view</a></li>
</ul>
</details>
<br />

Updates `no.nav.security:token-validation-spring-test` from 3.1.9 to
3.2.0
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/navikt/token-support/releases">no.nav.security:token-validation-spring-test's
releases</a>.</em></p>
<blockquote>
<h2>3.2.0</h2>
<h2>What's Changed</h2>
<ul>
<li>bump to 3.2, add parameters option to compiler (<a
href="https://redirect.github.com/navikt/token-support/issues/802">#802</a>)
<a
href="https://github.com/jan-olaveide"><code>@​jan-olaveide</code></a></li>
<li>ci: add workflow for auto-merging dependabot PRs (<a
href="https://redirect.github.com/navikt/token-support/issues/793">#793</a>)
<a href="https://github.com/tronghn"><code>@​tronghn</code></a></li>
</ul>
<h2>⬆️ Dependency upgrades</h2>
<ul>
<li>build(deps): bump com.nimbusds:oauth2-oidc-sdk from 11.6 to 11.7 (<a
href="https://redirect.github.com/navikt/token-support/issues/799">#799</a>)
<a
href="https://github.com/dependabot"><code>@​dependabot</code></a></li>
<li>build(deps): bump kotlin.version from 1.9.20 to 1.9.21 (<a
href="https://redirect.github.com/navikt/token-support/issues/796">#796</a>)
<a
href="https://github.com/dependabot"><code>@​dependabot</code></a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/navikt/token-support/commit/4e3c487118c451d56f984a6ef72499a15c522e70"><code>4e3c487</code></a>
Merge pull request <a
href="https://redirect.github.com/navikt/token-support/issues/802">#802</a>
from navikt/bump-32</li>
<li><a
href="https://github.com/navikt/token-support/commit/9b7d08cc6d634183a45979e0084aca8fb144d808"><code>9b7d08c</code></a>
parameters in mor modules</li>
<li><a
href="https://github.com/navikt/token-support/commit/e22d741dffe4850f9f6e567f8e4e809e372638b1"><code>e22d741</code></a>
typo in pom</li>
<li><a
href="https://github.com/navikt/token-support/commit/55d9b0e1981297e1800f7701388a653f50b241e6"><code>55d9b0e</code></a>
bump to 3.2, add paraeters option to compiler</li>
<li><a
href="https://github.com/navikt/token-support/commit/907d5957ccf07440b1d2ec0ce1d227a318e9b1fa"><code>907d595</code></a>
build(deps): bump com.nimbusds:oauth2-oidc-sdk from 11.6 to 11.7 (<a
href="https://redirect.github.com/navikt/token-support/issues/799">#799</a>)</li>
<li><a
href="https://github.com/navikt/token-support/commit/4cdec36b59812fc844bf5e2cd8db508f10388f10"><code>4cdec36</code></a>
parameters maven</li>
<li><a
href="https://github.com/navikt/token-support/commit/7f6b6969aca45e1a44f68d41ed36f587b17dd430"><code>7f6b696</code></a>
mvn</li>
<li><a
href="https://github.com/navikt/token-support/commit/0dc9fee78801dac9dadcf53342fb63326b6ccdc4"><code>0dc9fee</code></a>
fix login</li>
<li><a
href="https://github.com/navikt/token-support/commit/f6b06502238bde2276d8249c3cd4fa053b92826e"><code>f6b0650</code></a>
fix login</li>
<li><a
href="https://github.com/navikt/token-support/commit/892b828478f912ceb15855f80252df15a24ca570"><code>892b828</code></a>
build(deps): bump kotlin.version from 1.9.20 to 1.9.21 (<a
href="https://redirect.github.com/navikt/token-support/issues/796">#796</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/navikt/token-support/compare/3.1.9...3.2.0">compare
view</a></li>
</ul>
</details>
<br />

Updates `org.springframework.boot` from 3.1.5 to 3.2.0
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/spring-projects/spring-boot/releases">org.springframework.boot's
releases</a>.</em></p>
<blockquote>
<h2>v3.2.0</h2>
<h2>:star: New Features</h2>
<ul>
<li>Auto-configure observations for RestClients <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38500">#38500</a></li>
<li>Add support for Oracle Free, the replacement for Oracle XE, with
Testcontainers and Docker Compose <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38476">#38476</a></li>
<li>Provide dependency management for org.crac:crac <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38378">#38378</a></li>
<li>Add new properties for Liquibase 4.24.0 <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/38274">#38274</a></li>
<li>Provide a way to create custom ApplicationContextFactory in
SpringBootContextLoader <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38205">#38205</a></li>
<li>Report friendly error when failing to find AOT initializer <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/38188">#38188</a></li>
</ul>
<h2>:lady_beetle: Bug Fixes</h2>
<ul>
<li>Annotation based ConditionalOnBean checks can cause early
initialization of FactoryBeans <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38507">#38507</a></li>
<li>CRaC restoration fails when Actuator's running on a separate port <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38502">#38502</a></li>
<li>App that depends on Tomcat and on Jetty's websocket-server module
fails to start with IllegalStateException: WebSocketComponents has not
been created <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38286">#38286</a></li>
<li>App fails to start with a NoSuchMethodError when using Flyway 10.0.0
<a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38268">#38268</a></li>
<li>MeterRegistry throws BeanCreationNotAllowedException on shutdown <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38240">#38240</a></li>
<li>Resolution of productionRuntimeClasspath configuration may select
the wrong variant and contain a dependency's source jar <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38233">#38233</a></li>
<li>Docker JSON parsing fails on certain locales <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38220">#38220</a></li>
<li>FileNotFoundException is thrown serving resources due to
JarUrlConnection.getLastModified() returning zero <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38204">#38204</a></li>
<li>Failed to extract parameter names exception thrown when binding with
non-enumerable property source <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38201">#38201</a></li>
<li>Spring Boot 3.2.0-RC1 application fails on JDK with CRaC but without
a dependency on org.crac:crac <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38186">#38186</a></li>
<li>Missing configuration processing for PartEvent support <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/37642">#37642</a></li>
</ul>
<h2>:notebook_with_decorative_cover: Documentation</h2>
<ul>
<li>Document supported SQL comment prefixes <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38496">#38496</a></li>
<li>Update access log pattern documentation to align with changes in
Tomcat 10 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38425">#38425</a></li>
<li>Update Dynatrace docs with info about the meter metadata toggle <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/38368">#38368</a></li>
<li>Improve documentation regarding tracing in tests <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38362">#38362</a></li>
<li>Document the accepted inputs when configuring tags on
spring-boot:build-image and bootBuildImage <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38354">#38354</a></li>
<li>Document how to use cloudfoundry specific actuators with a custom
base path for webflux applications <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38353">#38353</a></li>
<li>Document Liberica JDK with CRaC <a
href="https://redirect.github.com/spring-projects/spring-boot/pull/38350">#38350</a></li>
<li>Add a Restarting a stopped or failed Job section to the batch howto
<a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38341">#38341</a></li>
<li>Clarify documentation on importing Testcontainer declarations and
using <code>@ServiceConnection</code> or
<code>@DynamicPropertySource</code> <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38337">#38337</a></li>
<li>Make distinction between Testcontainers for integration tests and
development more clear in documentation <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38336">#38336</a></li>
<li>When using Testcontainers at development time with
<code>@ServiceConnection</code> on a <code>@Bean</code> method, describe
when to use the name attribute and why <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38335">#38335</a></li>
<li>Fix link to Elasticsearch health indicator <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38334">#38334</a></li>
<li>Update Spring Framework documentation links <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38289">#38289</a></li>
<li>Code sample in &quot;Developing Your First Spring Boot
Application&quot; does not work <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38272">#38272</a></li>
<li>Improve --help and documentation for &quot;encodepassword
-a/--algorithm&quot; in the Spring Boot CLI <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38249">#38249</a></li>
<li>Add how-to documentation for test-only database migrations with
Flyway/Liquibase <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38231">#38231</a></li>
<li>Document that PEM content can be used directly in application.yaml
<a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38215">#38215</a></li>
<li>Document that TomcatConnectorCustomizers are not applied to
additional connectors <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38198">#38198</a></li>
</ul>
<h2>:hammer: Dependency Upgrades</h2>
<ul>
<li>Upgrade to AspectJ 1.9.20.1 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38358">#38358</a></li>
<li>Upgrade to Byte Buddy 1.14.10 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38407">#38407</a></li>
<li>Upgrade to DB2 JDBC 11.5.9.0 <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38408">#38408</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/f08a69e610faa92de2300853db71b428accd4dfa"><code>f08a69e</code></a>
Release v3.2.0</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/f3d48e64a5f4a310e694d6e83987f6db17af7632"><code>f3d48e6</code></a>
Set LATEST_GA to true for Homebrew and SDKMan</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/1514d6fd57c48f2ea1931c023ef9cdf2bf87b006"><code>1514d6f</code></a>
Upgrade to Spring Framework 6.1.1</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/0da9c642616a7223b6186eb43d4af03c5ba08249"><code>0da9c64</code></a>
Merge branch '3.1.x'</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/9552335c15a92d20a97dff28839809ade1b2ab06"><code>9552335</code></a>
Next development version (v3.1.7-SNAPSHOT)</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/f54a539c8690d9429deb739d2c55f92c1aa9da85"><code>f54a539</code></a>
Merge branch '3.1.x'</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/11db8c4a46e0786edab62faaeafbaa1d92bbda3a"><code>11db8c4</code></a>
Fix final release flag in CI pipeline</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/8f2d7d4ceffa9a09c89e65753d00738da7b8a80a"><code>8f2d7d4</code></a>
Merge pull request <a
href="https://redirect.github.com/spring-projects/spring-boot/issues/38508">#38508</a>
from izeye</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/f9f73aa14684f96b2e6fb699939b1857daeda2f7"><code>f9f73aa</code></a>
Polish</li>
<li><a
href="https://github.com/spring-projects/spring-boot/commit/f613ab89b9cb83ec19bc35fb63068f31e22c86a0"><code>f613ab8</code></a>
Auto-configure observations for RestClients</li>
<li>Additional commits viewable in <a
href="https://github.com/spring-projects/spring-boot/compare/v3.1.5...v3.2.0">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>