Bump the patch-dependencies group with 1 update (#642)
Bumps the patch-dependencies group with 1 update:
[org.postgresql:postgresql](https://github.com/pgjdbc/pgjdbc).

Updates `org.postgresql:postgresql` from 42.7.2 to 42.7.3
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/pgjdbc/pgjdbc/releases">org.postgresql:postgresql's
releases</a>.</em></p>
<blockquote>
<h2>v42.7.3</h2>
<h2>Changes</h2>
<ul>
<li>bump version to 42.7.4 <a
href="https://github.com/davecramer"><code>@​davecramer</code></a> (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3164">#3164</a>)</li>
<li>fix Issue boolean types not handled in SimpleQuery mode <a
href="https://github.com/davecramer"><code>@​davecramer</code></a> (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3146">#3146</a>)</li>
<li>The Gradle config enforces 17+ <a
href="https://github.com/OrangeDog"><code>@​OrangeDog</code></a> (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3147">#3147</a>)</li>
<li>Fix 2 changelog entry titles <a
href="https://github.com/crunchyjohn"><code>@​crunchyjohn</code></a> (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3142">#3142</a>)</li>
<li>chore: ensure CI jobs include tests for all the values of
preferQueryMode, ssl, xa, gss <a
href="https://github.com/vlsi"><code>@​vlsi</code></a> (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3137">#3137</a>)</li>
<li>update jdbc website security page with latest security advisory <a
href="https://github.com/davecramer"><code>@​davecramer</code></a> (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3135">#3135</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/pgjdbc/pgjdbc/blob/master/CHANGELOG.md">org.postgresql:postgresql's
changelog</a>.</em></p>
<blockquote>
<h2>[42.7.3] (2024-04-14 14:51:00 -0400)</h2>
<h3>Changed</h3>
<ul>
<li>chore: gradle config enforces 17+ [PR <a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3147">#3147</a>](<a
href="https://redirect.github.com/pgjdbc/pgjdbc/pull/3147">pgjdbc/pgjdbc#3147</a>)</li>
</ul>
<h3>Fixed</h3>
<ul>
<li>fix: boolean types not handled in SimpleQuery mode [PR <a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3146">#3146</a>](<a
href="https://redirect.github.com/pgjdbc/pgjdbc/pull/3146">pgjdbc/pgjdbc#3146</a>)
<ul>
<li>make sure we handle boolean types in simple query mode</li>
<li>support uuid as well</li>
<li>handle all well known types in text mode and change <code>else
if</code> to <code>switch</code></li>
</ul>
</li>
<li>fix: released new versions of 42.2.29, 42.3.10, 42.4.5, 42.5.6,
42.6.2 to deal with <code>NoSuchMethodError on
ByteBuffer#position</code> when running on Java 8</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/pgjdbc/pgjdbc/commit/818953a2b30480ecc874f812e46fcb82d1a395fd"><code>818953a</code></a>
fix Issue # 3145 boolean types not handled in SimpleQuery mode (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3146">#3146</a>)</li>
<li><a
href="https://github.com/pgjdbc/pgjdbc/commit/0e8ab636c505947dd1d3d32bdc0a7a2ee45f3545"><code>0e8ab63</code></a>
The Gradle config enforces 17+ (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3147">#3147</a>)</li>
<li><a
href="https://github.com/pgjdbc/pgjdbc/commit/b591b9fe8d9260b8ddae370323970eec26b1034b"><code>b591b9f</code></a>
Fix 2 changelog entry titles (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3142">#3142</a>)</li>
<li><a
href="https://github.com/pgjdbc/pgjdbc/commit/81844e6f3f907b1045b1c87da6e9e48bda39d522"><code>81844e6</code></a>
chore: ensure CI jobs include tests for all the values of
preferQueryMode</li>
<li><a
href="https://github.com/pgjdbc/pgjdbc/commit/2fada9ef4ec41b2c8a9ae12b431f57ca4b4e88aa"><code>2fada9e</code></a>
update security page (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3135">#3135</a>)</li>
<li><a
href="https://github.com/pgjdbc/pgjdbc/commit/388f0276f77a3ab363b180c09e45ca48569c3281"><code>388f027</code></a>
fix: typo password_encrypton -&gt; password_encryption in the error
message</li>
<li><a
href="https://github.com/pgjdbc/pgjdbc/commit/9cde4f52b4b3a3f9fd36231240381e9d5e6a02a7"><code>9cde4f5</code></a>
Update site for release of 42.7.2 (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3133">#3133</a>)</li>
<li><a
href="https://github.com/pgjdbc/pgjdbc/commit/df14e53b3f38b7f1aad04f2dd5a0c9b4f45a6249"><code>df14e53</code></a>
update version and last year modified</li>
<li>See full diff in <a
href="https://github.com/pgjdbc/pgjdbc/compare/REL42.7.2...REL42.7.3">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.postgresql:postgresql&package-manager=gradle&previous-version=42.7.2&new-version=42.7.3)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>